fix: pipeline

diff --git a/libs/.azure/build-and-test.yaml b/libs/.azure/build-and-test.yaml
--- a/libs/.azure/build-and-test.yaml
+++ b/libs/.azure/build-and-test.yaml
@@ -20,7 +20,7 @@ stages:
     # Note that the pyproject.toml is already copied into the docker image. Also note that copy
     # pasting the whole /app folder will overwrite the existing .venv folder in the docker image
     - script: |
-        docker run --rm -v $(pwd)/src:/app/src -v $(pwd)/flake8_dashboard:/app/flake8_dashboard -v $(pwd)/Makefile:/app/Makefile $DOCKER_IMAGE_NAME make lint
+        docker run --rm  -v $(pwd)/flake8_dashboard:/app/flake8_dashboard $DOCKER_IMAGE_NAME make lint
         LINTING_EXIT_CODE=$(echo $?)
         echo "LINTING_EXIT_CODE is equal to '${LINTING_EXIT_CODE}'."
         echo "##vso[task.setvariable variable=LINTING_EXIT_CODE]$LINTING_EXIT_CODE"
@@ -36,15 +36,16 @@ stages:
       displayName: "Publishing lint report"
     - script: |
         echo "LINTING_EXIT_CODE is equal to '${LINTING_EXIT_CODE}'."
-        if [ $LINTING_EXIT_CODE -eq 1 ]; then
-          echo "Linting failed ==> aborting pipeline ..."
-          exit 1
-        else
+        if [ $LINTING_EXIT_CODE -eq 0 ]; then
           echo "Linting successful ==> continuing pipeline ..."
+        else
+            echo "Linting failed ==> aborting pipeline ..."
+          exit $LINTING_EXIT_CODE
         fi
       displayName: "Linting successful check"
+
     - script: |
-        docker run --rm -v $(pwd)/src:/app/src -v $(pwd)/tests:/app/tests -v $(pwd)/htmlcov:/app/htmlcov -v $(pwd)/Makefile:/app/Makefile $DOCKER_IMAGE_NAME make coverage
+        docker run --rm -v $(pwd)/htmlcov:/app/htmlcov $DOCKER_IMAGE_NAME make coverage
       displayName: "Running unit tests with test coverage"
     - script: |
         zip -r $(Build.ArtifactStagingDirectory)/test_coverage.zip htmlcov
